source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'sqlite3'
gem 'bcrypt'
gem 'rerun'
gem 'byebug'
gem 'awesome_print'
gem 'sass'
gem 'sinatra-flash'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'minitest'
